import React, { useState } from 'react';
import { Alert, Button, Card, Form, Input, Space, Tag, Typography, App } from 'antd';
import { Enterprise } from './platformDomain';
import { changeEnterprise } from './platformStore';

export default function EnterpriseLogin({company,onLogin}:{company:Enterprise;onLogin:()=>void}){
  const [activating,setActivating]=useState(false);const {message}=App.useApp();
  return <div className="login-page"><Card className="login-card"><Space direction="vertical" size={20} style={{width:'100%'}}><div><Tag color="blue">企业管理端 · 演示</Tag><Typography.Title level={3}>{company.name}</Typography.Title><Typography.Text type="secondary">{activating?'设置登录密码，完成管理员激活':'登录企业管理端，管理企微托管与销售业务'}</Typography.Text></div>{!activating?<Form layout="vertical" initialValues={{account:company.adminLogin,password:'demo123456'}} onFinish={v=>{if(v.account.trim()!==company.adminLogin||v.password!==company.demoPassword){message.error('账号或密码错误');return;}if(!company.activated)setActivating(true);else onLogin();}}><Form.Item name="account" label="企业管理员账号" rules={[{required:true}]}><Input size="large" autoComplete="username"/></Form.Item><Form.Item name="password" label="密码" rules={[{required:true}]}><Input.Password size="large" autoComplete="current-password"/></Form.Item><Button block type="primary" htmlType="submit" size="large">登录</Button><Typography.Paragraph type="secondary" style={{marginTop:14,marginBottom:0,fontSize:12}}>初始演示密码：demo123456。首次登录需设置新密码。</Typography.Paragraph></Form>:<Form layout="vertical" onFinish={v=>{changeEnterprise(company.id,company.adminName,'激活企业管理员','完成首次登录激活',c=>({...c,activated:true,demoPassword:v.password}));onLogin();}}><Alert showIcon type="info" title="当前为产品演示，请勿使用真实工作密码。" style={{marginBottom:20}}/><Form.Item name="password" label="设置新密码" rules={[{required:true,min:6,message:'密码至少 6 位'}]}><Input.Password size="large" autoComplete="new-password"/></Form.Item><Form.Item name="confirm" label="确认新密码" dependencies={['password']} rules={[{required:true,message:'请再次输入密码'},({getFieldValue})=>({validator:(_,v)=>v===getFieldValue('password')?Promise.resolve():Promise.reject(new Error('两次密码不一致'))})]}><Input.Password size="large" autoComplete="new-password"/></Form.Item><Button type="primary" block size="large" htmlType="submit">激活并进入企业端</Button></Form>}<a href="./portal.html">返回演示入口</a></Space></Card></div>;
}
