import React from 'react';
import { Alert, App, Badge, Button, Card, Descriptions, Dropdown, Empty, Space, Table, Tabs, Tag } from 'antd';
import { ArrowLeftOutlined, CloudSyncOutlined, ExportOutlined, MoreOutlined } from '@ant-design/icons';
import { AuditEntry, Enterprise, seatUsage, serviceStatus } from '../shared/platformDomain';
import { applyLicense, changeEnterprise, configureLicense, enterpriseUrl } from '../shared/platformStore';
import { Metrics, Paragraph, ServiceTag, SyncTag, Text, Title } from './components';

export function LogTable({logs}:{logs:AuditEntry[]}){return <Table rowKey="id" size="middle" scroll={{x:860}} pagination={{pageSize:10,showSizeChanger:false,showTotal:t=>`共 ${t} 条记录`}} dataSource={logs} columns={[{title:'操作时间',dataIndex:'at',width:175},{title:'操作人',dataIndex:'actor',width:120},{title:'企业',dataIndex:'company',width:170},{title:'操作',dataIndex:'action',width:140},{title:'变更内容',dataIndex:'detail',width:350}]}/>;}
export default function EnterpriseDetail({company,logs,actor,onBack,onEdit,onDelivery}:{company:Enterprise;logs:AuditEntry[];actor:string;onBack:()=>void;onEdit:(mode:'seats'|'renew'|'open')=>void;onDelivery:()=>void}){
  const {message,modal}=App.useApp();const usage=seatUsage(company);const pending=company.revision!==company.appliedRevision;
  const doSync=()=>{try{applyLicense(company.id,actor);message.success('模拟同步完成，企业端授权已生效');}catch(e){message.error((e as Error).message);}};
  const toggleService=()=>{const stopped=company.license.status==='suspended';modal.confirm({title:stopped?'恢复企业服务？':'停用企业服务？',content:stopped?'恢复后需同步授权，企业可重新开启 AI。':'同步停用状态后将暂停 AI 托管与新增席位分配，保留账号及历史资料。',okText:stopped?'恢复服务':'停用服务',cancelText:'取消',okButtonProps:{danger:!stopped},onOk:()=>{configureLicense(company.id,{...company.license,status:stopped?'active':'suspended'},actor,stopped?'恢复服务':'主动停用服务');message.success('服务状态已更新，请同步授权');}});};
  const resetActivation=()=>modal.confirm({title:'重置企业管理员激活？',content:'当前演示密码将重置为 demo123456，企业管理员下次登录需重新设置密码。',okText:'确认重置',cancelText:'取消',onOk:()=>{changeEnterprise(company.id,actor,'重置管理员激活','重置初始演示密码',c=>({...c,activated:false,demoPassword:'demo123456'}));message.success('已重置激活');}});
  return <div className="po-page-stack"><Button type="text" icon={<ArrowLeftOutlined/>} onClick={onBack} className="po-back">返回企业列表</Button><div className="po-page-heading"><div><Space align="center"><Title level={3}>{company.name}</Title><ServiceTag company={company}/></Space><Paragraph type="secondary">{company.industry} · 企业编号 {company.id}</Paragraph></div><Space wrap><Button onClick={onDelivery}>交付信息</Button><Button onClick={()=>onEdit('renew')}>续期</Button><Button type="primary" onClick={()=>onEdit(company.license.status==='draft'?'open':'seats')}>{company.license.status==='draft'?'开通服务':'调整席位'}</Button><Dropdown menu={{items:[{key:'status',label:company.license.status==='suspended'?'恢复服务':'停用服务',danger:company.license.status!=='suspended',disabled:company.license.status==='draft'},{key:'activation',label:'重置管理员激活'}],onClick:({key})=>key==='status'?toggleService():resetActivation()}}><Button aria-label="更多企业操作" icon={<MoreOutlined/>}/></Dropdown></Space></div>
    <Metrics items={[{label:'授权席位',value:company.license.total,hint:'平台配置的托管额度'},{label:'已分配席位',value:usage.used,hint:`已同步 ${company.accounts.length} 个企微账号`},{label:'可分配席位',value:usage.remaining,hint:`企业端当前生效 ${usage.total} 席`},{label:'服务到期时间',value:<span className="po-date-value">{company.license.expiresAt}</span>,hint:`开始于 ${company.license.startsAt}`}]}/>
    <Alert type={pending?'warning':'success'} showIcon title={pending?'授权有更新，等待同步至企业端':'企业端授权已生效'} description={pending?`当前企业端生效 ${company.appliedLicense.total} 席，平台最新配置 ${company.license.total} 席。`:`最近同步：${company.syncedAt}`} action={<Button size="small" icon={<CloudSyncOutlined/>} onClick={doSync}>{pending?'模拟同步授权':'重新模拟同步'}</Button>}/>
    <Card className="po-detail-card"><Tabs defaultActiveKey="info" items={[
      {key:'info',label:'企业信息',children:<><Title level={5}>基本信息</Title><Descriptions column={{xs:1,sm:2}} items={[{key:'name',label:'企业名称',children:company.name},{key:'industry',label:'所属行业',children:company.industry},{key:'contact',label:'联系人',children:company.contact},{key:'phone',label:'联系电话',children:company.phone},{key:'created',label:'创建时间',children:company.createdAt},{key:'note',label:'备注',children:company.note||'—'}]}/><div className="po-section-divider"/><Title level={5}>部署与授权</Title><Descriptions column={{xs:1,sm:2}} items={[{key:'deployment',label:'部署方式',children:'客户独立部署（演示）'},{key:'sync',label:'授权状态',children:<SyncTag company={company}/>},{key:'link',label:'企业端入口',span:2,children:<Button type="link" style={{padding:0}} href={enterpriseUrl(company.id)} target="_blank" rel="noreferrer" icon={<ExportOutlined/>}>打开 {company.name} 管理端</Button>},{key:'identity',label:'部署标识',children:company.id},{key:'updated',label:'最近同步',children:company.syncedAt}]}/></>},
      {key:'seats',label:`席位使用（${usage.used}）`,children:<><Alert type="info" showIcon title="企微账号的席位分配与负责人配置由企业管理员操作；平台查看使用情况。" className="po-bottom-gap"/><Table rowKey="key" size="middle" scroll={{x:850}} dataSource={company.accounts} locale={{emptyText:<Empty description="企业尚未同步企微账号"/>}} pagination={{pageSize:8,showSizeChanger:false}} columns={[{title:'企微账号',dataIndex:'name',width:180,render:(name,a)=><><Text>{name}</Text><div className="po-subtext">{a.wecom}</div></>},{title:'所属部门',dataIndex:'department',width:120},{title:'负责人',dataIndex:'assignedUser',width:130,render:v=>v||<Text type="secondary">未分配</Text>},{title:'席位状态',dataIndex:'aiSeatEnabled',width:110,render:v=><Tag color={v?'processing':'default'}>{v?'已分配':'未分配'}</Tag>},{title:'AI 运行',width:110,render:(_,a)=><Badge status={a.aiSeatEnabled&&a.hosted&&['active','expiring'].includes(serviceStatus(company.appliedLicense))?'processing':'default'} text={a.aiSeatEnabled&&a.hosted&&['active','expiring'].includes(serviceStatus(company.appliedLicense))?'运行中':'已暂停'}/>},{title:'在线状态',dataIndex:'online',width:95,render:v=><Tag color={v?'success':'default'}>{v?'在线':'离线'}</Tag>},{title:'分配时间',dataIndex:'aiSeatOpenedAt',width:115,render:v=>v||'—'}]}/></>},
      {key:'admin',label:'企业管理员',children:<><Descriptions bordered column={1} items={[{key:'name',label:'管理员姓名',children:company.adminName},{key:'login',label:'登录账号',children:company.adminLogin},{key:'state',label:'激活状态',children:<Tag color={company.activated?'success':'warning'}>{company.activated?'已激活':'待首次登录激活'}</Tag>},{key:'reset',label:'账号操作',children:<Button onClick={resetActivation}>重置激活</Button>}]}/><Paragraph type="secondary" className="po-top-gap">初始管理员负责本企业人员和权限管理。初始演示密码为 demo123456。</Paragraph></>},
      {key:'logs',label:'操作记录',children:<LogTable logs={logs.filter(l=>l.companyId===company.id)}/>}
    ]}/></Card>
  </div>;
}
