import React, { useState } from 'react';
import { Alert, App, Button, Card, Form, Input, Modal, Select, Space, Switch, Table, Tag } from 'antd';
import { PlusOutlined } from '@ant-design/icons';
import { Operator } from '../shared/platformDomain';
import { saveOperator, uid } from '../shared/platformStore';
import { Paragraph, Title } from './components';

export default function OperatorPage({operators,current}:{operators:Operator[];current:Operator}){
  const [editing,setEditing]=useState<Operator|null>(null);const [form]=Form.useForm();const {message}=App.useApp();
  const open=(operator?:Operator)=>{const o=operator||{id:uid('op'),name:'',login:'',password:'demo123456',role:'operator' as const,enabled:true};setEditing(o);form.setFieldsValue(o);};
  const submit=async()=>{try{const values=await form.validateFields();if(!editing)return;saveOperator({...editing,...values},current.name);setEditing(null);message.success('平台账号已保存');}catch(e){if(e instanceof Error)message.error(e.message);}};
  return <div className="po-page-stack"><div className="po-page-heading"><div><Title level={3}>平台账号</Title><Paragraph type="secondary">管理我方运营人员及其操作权限。</Paragraph></div><Button type="primary" icon={<PlusOutlined/>} onClick={()=>open()}>新增账号</Button></div><Alert type="info" showIcon title="超级管理员可管理平台账号；运营专员可管理企业、服务授权和查看操作日志。"/><Card><Table rowKey="id" dataSource={operators} pagination={false} scroll={{x:750}} columns={[{title:'姓名',dataIndex:'name'},{title:'登录账号',dataIndex:'login'},{title:'角色',dataIndex:'role',render:role=><Tag color={role==='admin'?'blue':'default'}>{role==='admin'?'超级管理员':'运营专员'}</Tag>},{title:'账号状态',dataIndex:'enabled',render:(enabled,o)=><Switch checked={enabled} checkedChildren="启用" unCheckedChildren="停用" disabled={o.id===current.id} onChange={v=>{saveOperator({...o,enabled:v},current.name);message.success('账号状态已更新');}}/>},{title:'操作',render:(_,o)=><Button type="link" onClick={()=>open(o)}>编辑</Button>}]}/></Card><Modal title={operators.some(o=>o.id===editing?.id)?'编辑平台账号':'新增平台账号'} open={!!editing} onCancel={()=>setEditing(null)} onOk={submit} okText="保存" cancelText="取消"><Form form={form} layout="vertical"><Form.Item name="name" label="姓名" rules={[{required:true,whitespace:true,message:'请输入姓名'}]}><Input maxLength={20}/></Form.Item><Form.Item name="login" label="登录账号" rules={[{required:true},{pattern:/^[A-Za-z0-9_]{3,30}$/,message:'请输入 3～30 位字母、数字或下划线'}]}><Input disabled={editing?.id===current.id}/></Form.Item><Form.Item name="password" label="演示密码" rules={[{required:true,min:6,message:'密码至少 6 位'}]}><Input.Password autoComplete="new-password"/></Form.Item><Form.Item name="role" label="角色"><Select disabled={editing?.id===current.id} options={[{value:'admin',label:'超级管理员'},{value:'operator',label:'运营专员'}]}/></Form.Item></Form></Modal></div>;
}
