import React, { useEffect, useState } from 'react';
import { Alert, App, Avatar, Breadcrumb, Button, Card, ConfigProvider, Dropdown, Form, Input, Layout, Menu, Modal, Space, Tag } from 'antd';
import { ApartmentOutlined, ArrowRightOutlined, AuditOutlined, BankOutlined, CheckCircleOutlined, DownOutlined, KeyOutlined, LogoutOutlined, SafetyCertificateOutlined, SettingOutlined, TeamOutlined, UserOutlined } from '@ant-design/icons';
import zhCN from 'antd/locale/zh_CN';
import { Enterprise, Operator } from '../shared/platformDomain';
import { saveOperator, usePlatformData } from '../shared/platformStore';
import { Delivery, EnterpriseWizard, LicenseDialog, Paragraph, Text, Title } from './components';
import EnterpriseList from './EnterpriseList';
import EnterpriseDetail, { LogTable } from './EnterpriseDetail';
import OperatorPage from './OperatorPage';

const AUTH_KEY='sabuddy-platform-session';
function PlatformLogin({onLogin}:{onLogin:(id:string)=>void}){
  const data=usePlatformData();const [error,setError]=useState('');
  return <div className="po-login"><div className="po-login-story"><a href="./portal.html" className="po-login-brand"><span className="po-brand-symbol">S</span>Sabuddy<span className="po-brand-caption">企微智能销售</span></a><div className="po-story-content"><div className="po-eyebrow">PLATFORM OPERATIONS</div><h1>企业服务，<br/>统一管理。</h1><p>从企业开通到席位授权，<br/>让每一次交付清晰可控。</p><div className="po-flow-card"><div><span><BankOutlined/></span><b>企业入驻</b><small>签约企业统一开通</small></div><ArrowRightOutlined/><div><span><SafetyCertificateOutlined/></span><b>服务授权</b><small>额度与期限灵活配置</small></div><ArrowRightOutlined/><div><span><TeamOutlined/></span><b>企业使用</b><small>席位自主分配</small></div></div><div className="po-story-checks"><span><CheckCircleOutlined/> 独立管理入口</span><span><CheckCircleOutlined/> 授权全程可追踪</span></div></div><div className="po-login-footer">Sabuddy · 让 AI 按你的销售流程，持续跟进客户</div></div><div className="po-login-form"><div className="po-login-form-inner"><Tag color="blue" bordered={false}>平台运营端</Tag><Title level={2}>登录平台运营中心</Title><Paragraph type="secondary">面向平台管理员与运营人员</Paragraph><Form layout="vertical" initialValues={{login:'admin',password:'demo123456'}} onFinish={values=>{const operator=data.operators.find(o=>o.login===values.login.trim()&&o.password===values.password&&o.enabled);if(!operator){setError('账号或密码错误，或账号已停用');return;}setError('');onLogin(operator.id);}}><Form.Item label="登录账号" name="login" rules={[{required:true,message:'请输入登录账号'}]}><Input size="large" prefix={<UserOutlined/>} autoComplete="username"/></Form.Item><Form.Item label="密码" name="password" rules={[{required:true,message:'请输入密码'}]}><Input.Password size="large" prefix={<KeyOutlined/>} autoComplete="current-password"/></Form.Item>{error&&<Alert type="error" title={error} showIcon className="po-bottom-gap"/>}<Button type="primary" htmlType="submit" size="large" block>登录</Button></Form><div className="po-demo-credentials"><Text strong>演示账号</Text><span>管理员：admin / demo123456</span><span>运营专员：operator / demo123456</span></div><a href="./portal.html" className="po-return-link">返回演示入口 <ArrowRightOutlined/></a></div><Text type="secondary" className="po-login-demo-note">产品演示环境 · 数据仅保存在当前浏览器</Text></div></div>;
}
function PlatformWorkspace(){
  const data=usePlatformData();const {message}=App.useApp();
  const [userId,setUserId]=useState(()=>sessionStorage.getItem(AUTH_KEY)||'');
  const current=data.operators.find(o=>o.id===userId&&o.enabled);
  const [route,setRoute]=useState(()=>window.location.hash.slice(1)||'enterprises');
  const [wizard,setWizard]=useState(false);const [delivery,setDelivery]=useState('');
  const [editing,setEditing]=useState<{id:string;mode:'seats'|'renew'|'open'}|null>(null);
  const [passwordOpen,setPasswordOpen]=useState(false);const [passwordForm]=Form.useForm();
  useEffect(()=>{const update=()=>setRoute(window.location.hash.slice(1)||'enterprises');window.addEventListener('hashchange',update);return()=>window.removeEventListener('hashchange',update);},[]);
  const navigate=(target:string)=>{window.location.hash=target;setRoute(target);};
  const logout=()=>{sessionStorage.removeItem(AUTH_KEY);setUserId('');};
  if(!current)return <PlatformLogin onLogin={id=>{sessionStorage.setItem(AUTH_KEY,id);setUserId(id);}}/>;
  const details=route.startsWith('enterprise/')?data.enterprises.find(c=>c.id===decodeURIComponent(route.slice(11))):undefined;
  const menuKey=route.startsWith('enterprise/')?'enterprises':route;
  const title=({enterprises:'企业管理',seats:'托管席位管理',operators:'平台账号',logs:'操作日志'} as Record<string,string>)[menuKey]||'企业管理';
  const openEdit=(c:Enterprise,mode:'seats'|'renew'|'open')=>setEditing({id:c.id,mode});
  const navItems=[{key:'enterprises',icon:<BankOutlined/>,label:'企业管理'},{key:'seats',icon:<SafetyCertificateOutlined/>,label:'托管席位管理'},{key:'system',icon:<SettingOutlined/>,label:'系统管理',children:[...(current.role==='admin'?[{key:'operators',icon:<TeamOutlined/>,label:'平台账号'}]:[]),{key:'logs',icon:<AuditOutlined/>,label:'操作日志'}]}];
  return <Layout className="po-shell"><Layout.Sider className="po-sider" width={220} breakpoint="lg" collapsedWidth={64}><a href="./portal.html" className="po-sidebar-brand"><span className="po-brand-symbol">S</span><div><b>Sabuddy</b><small>平台运营中心</small></div></a><div className="po-sidebar-label">运营管理</div><Menu theme="light" selectedKeys={[menuKey]} defaultOpenKeys={['system']} mode="inline" items={navItems} onClick={({key})=>navigate(key)}/><div className="po-sidebar-bottom"><span className="po-online-dot"/> 产品演示环境<small>企业服务 · 集中管理</small></div></Layout.Sider><Layout><Layout.Header className="po-header"><Breadcrumb items={[{title:'平台运营中心'},{title},...(details?[{title:details.name}]:[])]}/><Space size={16}><a href="./portal.html" className="po-header-link">演示入口</a><Tag bordered={false}>演示版</Tag><Dropdown menu={{items:[{key:'password',label:'修改密码',icon:<KeyOutlined/>},{key:'logout',label:'退出登录',icon:<LogoutOutlined/>}],onClick:({key})=>{if(key==='logout')logout();else{passwordForm.resetFields();setPasswordOpen(true);}}}}><Button type="text"><Space><Avatar size={28} style={{background:'#e9effe',color:'#2867d9'}} icon={<UserOutlined/>}/>{current.name}<DownOutlined/></Space></Button></Dropdown></Space></Layout.Header><Layout.Content className="po-content">
    {details?<EnterpriseDetail company={details} logs={data.logs} actor={current.name} onBack={()=>navigate('enterprises')} onEdit={mode=>openEdit(details,mode)} onDelivery={()=>setDelivery(details.id)}/>:route==='logs'?<div className="po-page-stack"><div className="po-page-heading"><div><Title level={3}>操作日志</Title><Paragraph type="secondary">记录企业开通、授权调整、同步及席位分配的完整过程。</Paragraph></div></div><Card><LogTable logs={data.logs}/></Card></div>:route==='operators'&&current.role==='admin'?<OperatorPage operators={data.operators} current={current}/>:<EnterpriseList key={route==='seats'?'seats':'enterprises'} companies={data.enterprises} seatsView={route==='seats'} actor={current.name} onCreate={()=>setWizard(true)} onView={id=>navigate(`enterprise/${encodeURIComponent(id)}`)} onEdit={openEdit}/>}
  </Layout.Content></Layout><EnterpriseWizard open={wizard} onClose={()=>setWizard(false)} actor={current.name} onCreated={id=>{navigate(`enterprise/${encodeURIComponent(id)}`);setDelivery(id);}}/><LicenseDialog company={data.enterprises.find(c=>c.id===editing?.id)||null} mode={editing?.mode||'seats'} actor={current.name} onClose={()=>setEditing(null)}/><Delivery company={data.enterprises.find(c=>c.id===delivery)||null} onClose={()=>setDelivery('')}/><Modal title="修改平台登录密码" open={passwordOpen} onCancel={()=>setPasswordOpen(false)} okText="保存" cancelText="取消" onOk={async()=>{try{const v=await passwordForm.validateFields();if(v.old!==current.password){message.error('原密码不正确');return;}saveOperator({...current,password:v.password},current.name);setPasswordOpen(false);message.success('密码已修改');}catch{/* validation rendered */}}}><Form form={passwordForm} layout="vertical"><Form.Item name="old" label="原密码" rules={[{required:true,message:'请输入原密码'}]}><Input.Password/></Form.Item><Form.Item name="password" label="新密码" rules={[{required:true,min:6,message:'新密码至少 6 位'}]}><Input.Password autoComplete="new-password"/></Form.Item></Form></Modal></Layout>;
}
export default function PlatformApp(){return <ConfigProvider locale={zhCN} theme={{token:{colorPrimary:'#2867d9',borderRadius:7,colorBgLayout:'#f5f7fb',fontFamily:'Inter, "PingFang SC", "Microsoft YaHei", Arial, sans-serif'},components:{Table:{headerBg:'#f8f9fc',cellPaddingBlock:17},Menu:{itemHeight:44,itemSelectedBg:'#edf3ff'}}}}><App><PlatformWorkspace/></App></ConfigProvider>;}
